bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"
set-option -g default-terminal "screen-256color"
# if-shell 'uname | grep -q Darwin' 'set -g default-terminal "xterm-256color"'
# if-shell 'uname | grep -q Linux' 'set -g default-terminal "tmux-256color"'
# set-option -sa terminal-overrides ",*256col*:Tc"

set-option -g status-bg "#666666"
set-option -g status-fg "#aaaaaa"
set-option -g status-left-length 50

set-option -g history-limit 102400

set -g status-keys emacs

# 使用滑鼠
set-option -g mouse on
set -g set-clipboard off

# 在 status bar 的右側顯示：
#   1. 按下 prefix 的提示
#   2. 顯示時間
set -g status-right '#{prefix_highlight} | %Y-%m-%d %H:%M'

# index 從 0 變成 1
set -g base-index 1
# window 如果由新增、刪除時會自動重新計數
set -g renumber-windows on

##################################################################

unbind C-b
set -g prefix C-Space

bind C-Space send-prefix

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R

bind-key -T prefix  ';'  split-window -h
bind-key -T prefix  "'"  split-window -v

# copy mode
bind-key -T prefix          space       copy-mode
bind-key -T prefix          C-space       copy-mode
bind-key -T copy-mode-vi i send-keys -X cancel
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'xclip -se c -i'
bind-key -T copy-mode-vi    v           send -X begin-selection
bind-key -T copy-mode-vi    y           send -X copy-pipe-and-cancel 'xsel -ib'
bind-key -T copy-mode-vi    Escape      send -X cancel
bind-key -T copy-mode-vi    C-v         send -X rectangle-toggle
bind-key -T prefix          p           paste-buffer



