set -sg escape-time 0
setw -g mode-keys vi
# for windows terminal
set -ag terminal-overrides ',*:cud1=\E[1B'
bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"
# set-option -g default-terminal "screen-256color"
# if-shell 'uname | grep -q Darwin' 'set -g default-terminal "xterm-256color"'
if-shell 'uname | grep -q Linux' 'set -g default-terminal "tmux-256color"'
set-option -sa terminal-overrides ",*256col*:Tc"
                                       
set-option -g status-bg "#666666"
set-option -g status-fg "#aaaaaa"
set-option -g status-left-length 50

set-option -g history-limit 102400

set -g status-keys emacs

# 使用滑鼠
set-option -g mouse on
set -g set-clipboard off

# 在 status bar 的右側顯示：
#   1. 按下 prefix 的提示
#   2. 顯示時間
set -g status-right '#{prefix_highlight} | %Y-%m-%d %H:%M'

# index 從 0 變成 1
set -g base-index 1
# window 如果由新增、刪除時會自動重新計數
set -g renumber-windows on

##################################################################

unbind o
unbind C-b
set -g prefix C-Space

bind C-Space send-prefix

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# bind b select-pane -t {bottom}

bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R

bind-key -T prefix  'v'  split-window -h
bind-key -T prefix  "'"  split-window -v

# copy mode
## unbind left mouse drag copy 
unbind-key -T copy-mode-vi MouseDragEnd1Pane
## bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'xclip -se c -i'
bind-key -T copy-mode-vi MouseDown3Pane send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"
## Unbind the default context menu
unbind-key MouseDown3Pane
## Bind right-click to paste from the tmux buffer
bind-key -n MouseDown3Pane paste-buffer

bind-key -T prefix          space       copy-mode
bind-key -T prefix          C-space       copy-mode
bind-key -T copy-mode-vi i send-keys -X cancel
bind-key -T copy-mode-vi    v           send -X begin-selection
# bind-key -T copy-mode-vi    y           send -X copy-pipe-and-cancel 'xsel -ib' clip.exe
bind-key -T copy-mode-vi    y           send -X copy-pipe-and-cancel clip.exe 'xsel -ib' 
# bind-key -T copy-mode-vi    y           send -X copy-pipe clip.exe 'xsel -ib' 
bind-key -T copy-mode-vi    Escape      send -X cancel
bind-key -T copy-mode-vi    C-v         send -X rectangle-toggle
bind-key -T prefix          p           paste-buffer
bind-key -T prefix          c-p         paste-buffer


bind-key -T prefix N previous-window
bind-key -T prefix C-n next-window
bind-key -n C-M-h previous-window
bind-key -n C-M-l next-window

bind -n C-Up resize-pane -U 5
bind -n C-Down resize-pane -D 5
bind -n C-Left resize-pane -L 5
bind -n C-Right resize-pane -R 5

bind H swap-pane -s '{left-of}'
bind J swap-pane -s '{down-of}'
bind K swap-pane -s '{up-of}'
bind L swap-pane -s '{right-of}'

bind-key -n C-s resize-pane -Z

bind-key b break-pane -d 
bind-key d break-pane 
# bind-key @ join-pane -s hidden
bind-key "[" select-layout even-horizontal
bind-key "]" select-layout even-vertical
bind-key "o" last-window 
bind-key i join-pane -h -s '{marked}'

bind-key -T copy-mode-vi Escape send-keys -X clear-selection

# bind-key J choose-tree -Z "join-pane -s '%%'"
# hide pane
# join pane


